### ISSUE TITLE
import JSONJoy with CocoaPods 0.36.0.beta.1

### ISSUE THREAD

**Issue by alenofx** [daltoniam/JSONJoy-Swift#10]
Using CocoaPods 0.36.0.beta.1 the:
```swift
import JSONJoy
```
needs to be replaced with:
```swift
import JSONJoy_Swift
```
Probably the new **module_name** attribute in Podspec can help fixing this.

**Comment by daltoniam** [comment]
Thanks. I updated the podspec and this is now resolved.
