### ISSUE TITLE
Nested arrays .append

### ISSUE THREAD

**Issue by jasonpjohnson** [daltoniam/JSONJoy-Swift#11]
Flowing the instructions I am getting an error about missing the .append function

![image](https://cloud.githubusercontent.com/assets/2638146/5806748/25bf5136-9fea-11e4-9b1a-d75c09d134ad.png)

import Cocoa

struct Status_response :JSONJoy {
    var status: String?
    var issu: Issues?
    init(){}
    init(_ decoder: JSONDecoder){
        status = decoder["status"].string
        issu = Issues(decoder["issues"])
    }
}

struct Issues:JSONJoy {
    
    var issues: Array<Issue>?
    init(){}
    init(_ decoder: JSONDecoder){
        //we check if the array is valid then alloc our array and loop through it, creating the new address objects.
        if let issu = decoder["issues"].array {
            issues = Array<Issue>()
            for issuDecoder in issu {
                issues += Issue(issuDecoder)
            }
        }
    }
}

struct Issue:JSONJoy {
    var id: Int?
    var skill_name : String?
    var problem : String?
    var priority : Int?
    init(){}
    init(_ decoder: JSONDecoder){
        id = decoder["id"].integer
        skill_name = decoder["skill_name"].string
        problem = decoder["problem"].string
        priority = decoder["priority"].integer
    }
}

**Comment by jasonpjohnson** [comment]
I fixed it in my code with this 

struct Issues:JSONJoy {
    
    var issues: Array<Issue> = []
    init(){}
    init(_ decoder: JSONDecoder){
        //we check if the array is valid then alloc our array and loop through it, creating the new address objects.
        if let issu = decoder["issues"].array {
            //issues = Array<Issue>()
            for issuDecoder in issu {
                issues.append(Issue(issuDecoder))
            }
        }
    }
}

**Comment by daltoniam** [comment]
Glad to hear it and good work.

**Comment by jasonpjohnson** [comment]
Thanks!

I'm still having problems returning my my nested array of issues. In this line  issues = Issues(decoder["issues"]) I get that the key issues doesn't exist

--- Here is my json 
{
status: "4D Is Down",
issues: [
{
id: "1",
skill_name: "4D",
problem: "Can not process invoice",
priority: "10"
},
{
id: "2",
skill_name: "OfficeLink",
problem: "Can not auto dial",
priority: "10"
}
]
}


--- Here is the full class(s)
import Cocoa

struct Status_response :JSONJoy {
    var status: String?
    var issues: Issues?
    init(){}
    init(_ decoder: JSONDecoder){
        status = decoder["status"].string
        issues = Issues(decoder["issues"])
    }
}

struct Issues:JSONJoy {
    
    var issues: Array<Issue> = []
    init(){}
    init(_ decoder: JSONDecoder){
        //we check if the array is valid then alloc our array and loop through it, creating the new address objects.
        if let issu = decoder["issues"].array {
            issues = Array<Issue>()
            for issuDecoder in issu {
                issues.append(Issue(issuDecoder))
            }
        }
    }
}

struct Issue:JSONJoy {
    var id: Int?
    var skill_name : String?
    var problem : String?
    var priority : Int?
    init(){}
    init(_ decoder: JSONDecoder){
        id = decoder["id"].integer
        skill_name = decoder["skill_name"].string
        problem = decoder["problem"].string
        priority = decoder["priority"].integer
    }
}

any thoughts ?
The status returns just fine

**Comment by daltoniam** [comment]
I think I see the problem. You are requesting the "issues" twice. Once at:
```swift
issues = Issues(decoder["issues"])
```
and at:

```swift
if let issu = decoder["issues"].array {
```

Try changing it to:

```swift
if let issu = decoder.array {
```

**Comment by jasonpjohnson** [comment]
Thanks!!!
Have a beer on me!!

Jason Johnson

**Comment by daltoniam** [comment]
@jasonpjohnson thanks! Appreciate it!

**Comment by jasonpjohnson** [comment]
Last question, I can't figure out how to iterate over the array of issues now I would have thought that it would be something like this.

                var status = Status_response(JSONDecoder(data))
                for issue : Issue in status.issues {
                    println(issue.problem!)
                }

any thoughts?

**Comment by daltoniam** [comment]
I would think it should be:
```swift
for issue in status.issues {
    println(issue.problem!)
}
```
The type should already be inferred from the generic type in the array. Might need to do: ```status.issues!``` if it is an optional, or better yet use the ```if let``` unwrapping.

**Comment by jasonpjohnson** [comment]
I get i 'issues' does not have a member named 'Generator'

**Comment by daltoniam** [comment]
Maybe try this:
```swift
if let issues = status.issues {
   for issue in issues {
        println(issue.problem!)
   }
}
```

**Comment by jasonpjohnson** [comment]
I get Type 'Issues' does not conform to protocol sequenceType

**Comment by daltoniam** [comment]
ah ok. Yeah I think I know what it is now. ```Issues``` is your class name and it has a variable inside named ```issues``` (queue the inception horn).  Try this:

```swift
if let issues = status.issues!.issues {
   for issue in issues {
        println(issue.problem!)
   }
}
```

Also I might recommend refactoring and removing the extra ```Issues``` struct. I think you might be able to just create an ```issues``` array of ```Issue``` objects in the ```Status_response``` struct.

**Comment by jasonpjohnson** [comment]
Thank again. 
I refactored it down, I was trying to figure out what to do based on the top of the documentation about addresses and the bottom about an array of multiple address..that sillyness got lost in the translation.

Thank you very much I just rewrote my app to use swiftHTTP and JSONJoy ...it is much better now!

Jason

**Comment by daltoniam** [comment]
Awesome, nicely done. I bet it is, but I might be a tad bias :smile:
