### ISSUE TITLE
JSONJoy on real device

### ISSUE THREAD

**Issue by javierC1988** [daltoniam/JSONJoy-Swift#13]
Hi, I followed the instructions for allowing build app in a real iphone, but can't do it.
Here is my screen capture
![error_xcodejson](https://cloud.githubusercontent.com/assets/9955461/6566287/0a8ba834-c686-11e4-87cc-6f7d30ad86fb.png)

**Comment by daltoniam** [comment]
I might try cleaning the project or doing a "clean project folder" by holding option when doing clean (Command-Option-Shift-K).

**Comment by javierC1988** [comment]
Thanks Dalton!! I got it yesterday few minutes after writing!!
Nice work with libraries, want to support project!!

**Comment by daltoniam** [comment]
Awesome, thanks!
