### ISSUE TITLE
JSONDecoder.description not json valid

### ISSUE THREAD

**Issue by paztis** [daltoniam/JSONJoy-Swift#14]
In case of a NSNull object value, description call returns <null> instead of null.
For example it returns 
<code> { "test": <null> } </code>
instead of 
<code> { "test": null } </code>

With this problem, it's not possible to create a new JSONDecoder from the description: 
<code>let desc = jsonDecoder1.description</code>
<code>let nsData = (desc as NSString).dataUsingEncoding(NSUTF8StringEncoding) </code>
<code>let jsonDecoder2 = JSONDecoder(nsData!)</code>
jsonDecoder2 is failed if there is a null value...

**Comment by daltoniam** [comment]
alright, I will look into it, probably need to add an else here:
https://github.com/daltoniam/JSONJoy-Swift/blob/master/JSONJoy.swift#L165

**Comment by daltoniam** [comment]
I checked in a possible fix to master. Let me know if it fixes it.
