### ISSUE TITLE
JSONJoy-Swift version prior to 7.0

### ISSUE THREAD

**Issue by gamugamu** [daltoniam/JSONJoy-Swift#15]
Hi daltoniam, you specified that your library works in iOS 7.0, but it is specified as 8.0 minimum requirement in cocoapod. Is there limitation in 7.0 ?

**Comment by daltoniam** [comment]
The CocoaPods is at iOS 8 as xCode does not support dynamic frameworks until iOS 8. The code will work in iOS 7 if you pull the source in directly.
