### ISSUE TITLE
Some User model, different JSON keys?

### ISSUE THREAD

**Issue by Werbelow** [daltoniam/JSONJoy-Swift#16]
I am using JSONJoy and SwiftHTTP, both are awesome, thanks! 

Everything works great when using SwiftHTTP to create a local account (ie not using FB). However when using facebook login, the JSON object returns slightly different keys

For example, our local API returns `firstName : Travis`  FB returns `first_name : Travis` 

I would like to use the same User model if possible and was wondering if there is a way I can assign `firstName` to either `decoder["firstName"].string` or `decoder["first_name"].string` depending on if I sent the local User object or the FB user object.

Cheers,
-Travis

**Comment by daltoniam** [comment]
Glad to hear it is helping out! Could you do something as simple as:

```swift
struct User {
    var objID: Int?
    var firstName: String?
    var lastName: String?
    init(_ decoder: JSONDecoder) {
        objID = decoder["id"].integer
        if let first = decoder["first_name"].string {
            firstName = first
        } else {
            firstName = decoder["firstName"].string
        }
        lastName = decoder["last_name"].string
        age = decoder["age"].integer
        address = Address(decoder["address"])
    }
}
```

**Comment by Werbelow** [comment]
Might be the fastest reply to a Github issue I've ever had! 

That worked perfectly, thanks so much!
