### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by OmarBizreh** [daltoniam/JSONJoy-Swift#20]
Hi, I have the following JSONDecoder:
Optional({
    AppUserId = "JSONJoy.JSONDecoder";
    ContentToDisplay = "JSONJoy.JSONDecoder";
    CreationDate = "JSONJoy.JSONDecoder";
    ExiprationDate = "JSONJoy.JSONDecoder";
    IsSeenByUser = "JSONJoy.JSONDecoder";
    NotificationContent = "JSONJoy.JSONDecoder";
    NotificationID = "JSONJoy.JSONDecoder";
    NotificationType = "JSONJoy.JSONDecoder";
    SISUserID = "JSONJoy.JSONDecoder";
    SISUserNumber = "JSONJoy.JSONDecoder";
})

All keys return a value except for "NotificationContent" it returns another JSON. I was able to get all values by using: decoder["AppUserID"] for example, but for NotificationContent I had to read it as String, convert it to NSData then decode it using JSONDecoder, using decoder["NotificationContent"] just didn't work. Below is my full code, it would be great if you let me know what I'm doing wrong

``` Swift
 let resultDecoder = JSONDecoder(response)[resultKey];
        let serverResponse = ServerResponseModel(resultDecoder);
        if serverResponse.Result == 0 {
            var resultArray: Array<JSONDecoder>? = resultDecoder["OperationData"].array;
            if let arr = resultArray {
                for i in arr {
                    let jsonNotificationType = i["NotificationType"].integer!;
                    let jsonMessage: JSONDecoder = i["NotificationContent"]; // This did not work, it was treated like i["NotificationContent"] value was sent as a String and not NSData (if you recall my last issue I provided it's link below the code) 
                    // For some reason we must decode NotificationContenet again like shown below
                    let x = (i["NotificationContent"].string! as NSString).dataUsingEncoding(NSUTF8StringEncoding);
                    switch jsonNotificationType{
                    case 0:
                        let messageModel = MessageModel(JSONDecoder(x!));
                    break;
                 }
               }
```

[Link to my previous issue in-case it can help] (https://github.com/daltoniam/JSONJoy-Swift/issues/18)

**Comment by daltoniam** [comment]
The `notificationContent` key has a string of JSON with it? Can you provide an example of what it looks like? JSONJoy uses the builtin NSJSONSerialization class, so if that parses it as an object and not a string, it should behave properly.

**Comment by OmarBizreh** [comment]
Here is a sample of ```NotificationContent```:
``` JSON
"NotificationContent":"{\"Subject\":{\"SubjectTitle\":\"Physical Development\",\"ExamMark\":null,\"ClassTimeFrom\":null,\"ClassTimeTo\":null,\"SubjectID\":null,\"MaxGrade\":0} 
```

And this is the JSON Object that I parse using JSONDecoder it includes ```NotificationContent```:
``` JSON
{"AppUserId":"0000000-0000-0000-0000-000000000000","ContentToDisplay":null,"CreationDate":"\/Date(1436337714830+0300)\/","ExiprationDate":"\/Date(1437201714830+0300)\/","IsSeenByUser":false,"NotificationContent":"{\"Subject\":{\"SubjectTitle\":\"Language and Literacy Development\",\"ExamMark\":null,\"ClassTimeFrom\":null,\"ClassTimeTo\":null,\"SubjectID\":null,\"MaxGrade\":0},\"Homework\":{\"Title\":\"Quiz\",\"CreationDate\":\"08\/07\/2015 9:41:54 AM\",\"Description\":\"Quiz in chapter 10, pages 145 -> 200\"},\"TeacherNotes\":{\"TeacherName\":\"\",\"CreationDate\":\"08\/07\/2015 9:41:54 AM\",\"Content\":\"None\"},\"DueDate\":\"09\/07\/2015\",\"TimeFrom\":\"8:00 AM\",\"TimeTo\":\"9:30 AM\",\"child\":{\"FullName\":\"شهاب\",\"PersonID\":\"00000000-0000-0000-0000-000000000000\",\"SISNumber\":\"8136-1816103\"},\"Title\":\"Quiz\"}","NotificationID":"0000000-0000-0000-0000-000000000000","NotificationType":10,"SISUserID":"0000000-0000-0000-0000-000000000000","SISUserNumber":"0000-0000"}
```

By the way a side question, in my pod file I chose the platform to be IOS 7, am I good to go for both IOS 7 & 8? or are there any changes I need to do for both JSONJoy and SwiftHTTP?

**Comment by daltoniam** [comment]
Alright, yeah. I don't think NSJSONSerialization parses a JSON string with JSON. You will probably have to run that through the parser again (or a JSONDecoder), as JSONJoy uses the standard NSJSONSerialization API to do JSON parsing. 

You should be able to set it to iOS7 for both. The code isn't any different for either target version. The only issue is iOS 7 doesn't support Swift dynamic frameworks. See this for more info:

https://github.com/CocoaPods/swift/issues/9
