### ISSUE TITLE
Impossible to extend

### ISSUE THREAD

**Issue by C4Grey** [daltoniam/JSONJoy-Swift#21]
Hi!
I've used your library via CocoaPods and faced a problem with adding of new types via extension mechanism: since [variable "value" is not public](https://github.com/daltoniam/JSONJoy-Swift/blob/d9e8eca2bf4f2c2d49f98fa2f94cf1a47e375d8e/JSONJoy.swift#L13), it is impossible to write an extension(for example, for UInt64 support):
````swift
public extension JSONDecoder {
    public var unsignedLong: UInt64? {
        return (value as? NSNumber)?.unsignedLongLongValue
    }
}
````
because "value" is an internal field of the JSONDecoder class and is available only inside it's module.

**Comment by daltoniam** [comment]
yeah, I hadn't intend for value to be public, but I can see how the would be an issue to extend it. I guess it boils down to if we need to add more methods to handle the different types or we could just add a readonly property that access value directly. I think it would be the best of both needs if we did that.

**Comment by daltoniam** [comment]
I checked in a fix for this. Added a new property named `rawValue`.

```swift
public extension JSONDecoder {
    public var unsignedLong: UInt64? {
        return (rawValue as? NSNumber)?.unsignedLongLongValue
    }
}
```

I will also add this to docs and make a new release for CocoaPods.
