### ISSUE TITLE
swift 2.0 : toInt() method is given a error. Because,In Swift 2.x, the .toInt() function was removed from String

### ISSUE THREAD

**Issue by cczufish** [daltoniam/JSONJoy-Swift#24]
if lower == "true" || lower.toInt() > 0 {

swift 2.0 : toInt() method is given a error. Because,In Swift 2.x, the .toInt() function was removed from String

**Comment by cczufish** [comment]
if lower == "true" || Int(lower) > 0 {

**Comment by cczufish** [comment]
http://stackoverflow.com/questions/30739460/toint-removed-in-swift-2

**Comment by acmacalister** [comment]
Please try the Swift 2 branch. If that has issues as it was built against an older version of the beta we can get it updated.

**Comment by cczufish** [comment]
ok ,thank you !@acmacalister

**Comment by acmacalister** [comment]
:+1:
