### ISSUE TITLE
JSONJoy.swift:159:31: 'advance' is unavailable: call the 'advancedBy(n)' method on the index

### ISSUE THREAD

**Issue by cczufish** [daltoniam/JSONJoy-Swift#25]
JSONJoy.swift:159:31: 'advance' is unavailable: call the 'advancedBy(n)' method on the index

            str.removeAtIndex(advance(str.endIndex, -1))

**Comment by cczufish** [comment]
str.removeAtIndex(str.endIndex.advancedBy(-1))
http://stackoverflow.com/questions/32237243/advancedby-api-in-swift-2-0

**Comment by elvinaze** [comment]
advance(indexOfString, 1)
indexOfString.advancedBy(1)
