### ISSUE TITLE
JSONJoy.swift:170:20: Immutable value 'str' was never used; consider replacing with '_' or removing it

### ISSUE THREAD

**Issue by cczufish** [daltoniam/JSONJoy-Swift#26]
JSONJoy.swift:170:20: Immutable value 'str' was never used; consider replacing with '_' or removing it

**Comment by acmacalister** [comment]
We already have a Swift 2 branch that can use. Please stop opening issues for each error.

**Comment by cczufish** [comment]
where is the branch 2.0 ,thank you !

**Comment by acmacalister** [comment]
https://github.com/daltoniam/JSONJoy-Swift/tree/swift-2

**Comment by cczufish** [comment]
@acmacalister  this branch can not use cocoapods ?

**Comment by acmacalister** [comment]
Yeah, you just need to use the branch syntax in your Podfile like so:

`pod 'JSONJoy-Swift', :git => 'https://github.com/daltoniam/JSONJoy-Swift', :branch => 'swift-2'`

**Comment by cczufish** [comment]
my podfile is 

platform :ios, '8.0'
use_frameworks!
pod 'JSONJoy-Swift', :git => 'https://github.com/daltoniam/JSONJoy-Swift', :branch => 'swift-2'

then pod install

Pre-downloading: `JSONJoy-Swift` from `https://github.com/daltoniam/JSONJoy-Swift`, branch `swift-2`
Downloading dependencies
Installing JSONJoy-Swift (0.9.3)
