### ISSUE TITLE
decoder.getArray(&scopes) not working .. 

### ISSUE THREAD

**Issue by rosevinod** [daltoniam/JSONJoy-Swift#28]
decoder.getArray(&scopes) its giving me nil value .....

**Comment by rosevinod** [comment]
as this was not working : decoder.getArray(&scopes) .. i mean how to get all the array back to my view controller: i used instead this to get the array

struct ResponseData : JSONJoy {
    var ambulance:[String] = []

    init(_ decoder: JSONDecoder) {
        if let addrs = decoder["ambulance"].array {
            for addrDecoder in addrs {
                //print("addrDecoder \(addrDecoder.string!)")
                ambulance.append(addrDecoder.string!)
            }
        }// end if
       
    }// end init decoder
    
}// end ResponseData

**Comment by daltoniam** [comment]
Can you share what your JSON structure looks like? I don't what is wrong in the parsing logic if I don't have the source :smile:.

**Comment by rosevinod** [comment]
following is the JSON ... let me how to get doctors array out of it.

{
  "statusCode": 200,
  "status": "success",
  "responseData": {
    "uri": "http://........./provider_categories/",
    "doctor": [
      "Ayurveda",
      "Cardiologist",
      "Dentist",
      "Dermatologist",
      "Ent",
      "Gastroenterologist",
      "Gynaecologist",
      "Hematologist",
      "Homeopathy",
      "Neurologist",
      "Nutritionist",
      "Oncologist",
      "Orthopedic",
      "Paediatric",
      "Physician",
      "Physiotherapist",
      "Psychiatrist",
      "Urologist",
      "Veterinary"
    ],
    "pharmacy": [
      "24 hrs Pharmacy",
      "Ayurvedic Pharmacy"
    ],
    "ambulance": [
      "Ambulance Services",
      "24 hrs Ambulance Services",
      "Air Ambulance",
      "Blood Bank",
      "24 hrs Blood Bank"
    ]
  }
}

**Comment by daltoniam** [comment]
```swift
struct ResponseData : JSONJoy {
var doctors:[String] = []
init(_ decoder: JSONDecoder) { 
   if let respData = decoder["responseData"]. dictionary  { //not sure if you are passing the JSON straight in or not, but acc
     respData["doctors"].getArray(&doctors)
   }
}
}
```

or you can do it the object way:

```swift
struct ResponseData : JSONJoy {
var doctors:[String] = []
init(_ decoder: JSONDecoder) { 
   if let respData = decoder["responseData"]. dictionary  { 
     if let docs = decoder["doctors"].array {
            for doc in docs {
                doctors.append(doc.string)
            }
        }
   }
}
}
```
I just made these off hand, but should give the basic idea.

**Comment by rosevinod** [comment]
I got following error for : 

-- > Cannot invoke 'getArray' with an argument list of type '(inout [String])'

 I don't think : getArray working correctly.. alternative must be use. Please update your document reference to avoid any confusion.

struct ResponseData : JSONJoy {
var doctors:[String] = []
init(_ decoder: JSONDecoder) { 
   if let respData = decoder["responseData"]. dictionary  { //not sure if you are passing the JSON straight in or not, but acc
     respData["doctors"].getArray(&doctors)
   }
}
}

**Comment by daltoniam** [comment]
`getArray` requires a optional array so it would be `var doctors: [String]?` in order to work, should have been clearer. I will update the docs to avoid the confusion.
