### ISSUE TITLE
Want to use it on watchos 2

### ISSUE THREAD

**Issue by evgeniynet** [daltoniam/JSONJoy-Swift#30]
Hi, I want to use it on watch os, how its possible?

now i got Target 'JSONJoy-Swift' of project 'Pods' was rejected as an implicit dependency for 'JSONJoy.framework' because it doesn't contain platform 'watchsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'

**Comment by daltoniam** [comment]
I haven't tried building JSONJoy in a watchOS project yet. I will try to do that soon, pull request welcomed.

**Comment by daltoniam** [comment]
`2.0.0` should provided support for this now.
