### ISSUE TITLE
How to parse a string using JSONJoy?

### ISSUE THREAD

**Issue by basharov** [daltoniam/JSONJoy-Swift#31]
For testing purpose I need to translate a string like  `"{\"ip\": \"128.74.141.82\"}"` to an object, imitating server's response. 

How can it be done?

**Comment by daltoniam** [comment]
You could just pass your string into a `JSONDecoder` instance and then pass that decoder object into your struct/class that implements the JSONJoy protocol. A full server to client example here:

https://github.com/daltoniam/SwiftHTTP#clientserver-example

**Comment by vrutberg** [comment]
As a newcomer to this library, I expect something like this to work:

`JSONDecoder("{\"value\": 2}")["urlscheme"].integer`

But it doesn't. It returns nil. I'm suspecting a complete example in this fashion is what @basharov suggests.

**Comment by daltoniam** [comment]
Ah ok. I hadn't considered a string being passed like that as normally a response comes back as an NSData object. I checked in a change that will support something like this, although I still would recommend using NSData when possible as to save from having to convert back to NSData to use the NSJSONSerialization parsing.
