### ISSUE TITLE
Using JSONJoy with Realm

### ISSUE THREAD

**Issue by reshadf** [daltoniam/JSONJoy-Swift#33]
Hi, I'd like to use Realm together with JSONJoy. 

I don't want to create separate objects for both the libraries. Is it possible somehow to use 1 object for both libs? Since Realm objects are classes that inherit from OBJECT. 

    class Dog: Object {
      dynamic var name = ""
      dynamic var age = 0
    }

Do you have tips and solutions on this? :)

**Comment by daltoniam** [comment]
JSONJoy is a protocol, so you could just do:

```
class Dog: Object, JSONJoy {
//realm stuff and JSONJoy init method
}
```

That should work fine from the JSONJoy side of things

**Comment by reshadf** [comment]
thanks I'll give it a try! should have checked what JSONJOy was ;)
