### ISSUE TITLE
version mismatch in README

### ISSUE THREAD

**Issue by sanghviharshit** [daltoniam/JSONJoy-Swift#36]
Gives this error when trying to follow the instructions in README.

```
[!] Unable to satisfy the following requirements:

- `JSONJoy-Swift (~> 1.1.0)` required by `Podfile`
```

The latest release is 1.0.1 and using this version number in podfile solves the issue.

**Comment by daltoniam** [comment]
Thanks, I forgot to properly update the README for the new version. I ended up changing it to 2.0.0.
