### ISSUE TITLE
[FeatureRequest] Add ability to decode JSONJoy object

### ISSUE THREAD

**Issue by SASDOE** [daltoniam/JSONJoy-Swift#37]
For various purposes I think JSONJoy would greatly benefit from having the ability to return a JSON String (ie `let jsonString: String = myObject.getJSONString()`)

**Comment by daltoniam** [comment]
JSONJoy already has this feature, it just isn't documented. Call `print()` on any decoder object you want. It will return the JSON string for the JSON structure that decoder represents.
