### ISSUE TITLE
Gracefully handling JSON's null

### ISSUE THREAD

**Issue by libjared** [daltoniam/JSONJoy-Swift#38]
I'm reading JSON from a server. A key in the decoder has a possibility to be either an integer or a JSON null. I'd like for it to easily be turned into a Swift Int?. Here's how I handle that, in an extension:

    public func getIntOptional() throws -> Int? {
        if isNull() {return nil}
        guard let i = integer else {throw JSONError.WrongType}
        return i
    }

    public func isNull() -> Bool {
        if let raw = rawValue {
            if let rawNS = raw as? NSObject {
                if rawNS == NSNull() {
                    return true
                }
            }
        }
        return false
    }

This seems kind of clumsy, especially the forced unwrapping and casting. Is there a better way?

**Comment by daltoniam** [comment]
I might recommend trying:
```
yourOptionalInt = decoder["your_key"].integer
```

That would either set the optional int to the proper value or nil if NSNull or if the key couldn't be found.
