### ISSUE TITLE
Example code issues

### ISSUE THREAD

**Issue by torokzsolt** [daltoniam/JSONJoy-Swift#42]
Hi there!

While trying out this amazing tool I noticed two small, and easy to fix issue:
 - missing `,` character in addresses JSON array after id (both in user and array example)
 - postal code is defined as String on swift, but represented as number in JSON

Should I create a pr or will you handle this?

**Comment by daltoniam** [comment]
Apologizes on the delay. I updated the README, thanks for the report!
