### ISSUE TITLE
Bool parsing broken on XCode 8.1

### ISSUE THREAD

**Issue by blalger** [daltoniam/JSONJoy-Swift#47]
"open var bool: Bool" is broken on XCode 8.1

The underlying json parsing library is now returning the Bool type when parsing my server bool responses.  Simple fix, I made this small change locally as a workaround:

```
///treat the value as a bool
open var bool: Bool {
    if let val = self.value as? Bool {
        return val
    } else if let str = self.string {
        let lower = str.lowercased()
        if lower == "true" || Int(lower) > 0 {
            return true
        }
    } else if let num = self.integer {
        return num > 0
    } else if let num = self.double {
        return num > 0.99
    } else if let num = self.float {
        return num > 0.99
    }
    return false
}
```

**Comment by vrutberg** [comment]
I'm experiencing the same issue, the bool property always seem to return false as of Xcode 8.1.

**Comment by daltoniam** [comment]
Thanks for the PR. Version `2.1.0` has been released with the update.
