### ISSUE TITLE
Ambiguous use of 'getString()'

### ISSUE THREAD

**Issue by kyc3** [daltoniam/JSONJoy-Swift#49]
Hi,

with version 2.1.0 I am unable to use the framework as for example

`jsonDecoder["MyKey"].getString()`

fails, as there is one getString() that throws and one that returns an optional.

EDIT: This is also true for `getInt()` etc.

Best regards

**Comment by alpreu** [comment]
Having the same error

**Comment by kyc3** [comment]
I solved the issue and submittied a pull request, so there may be a quick fix for that :)

**Comment by daltoniam** [comment]
Thanks for the report and PR. I ended up refactor the library to be simpler and much cleaner imho. Version 3.0.0, let me know if you have any issues or concerns.
