### ISSUE TITLE
Handling optional array

### ISSUE THREAD

**Issue by chriskan0305** [daltoniam/JSONJoy-Swift#51]
Hi Dalton,

This is a great tool. Thanks.

I encountered a scenario.

String? can use getOptional() to obtain string
[String]? will result in nil

How to resolve? Or did I miss something.

**Comment by altagir** [comment]
I confirm the issue... optionalArray also always return nil

**Comment by daltoniam** [comment]
Hrm, I hadn't considered doing something like this. I just checked in a possible fix to master. Let me know if that fixes it!

**Comment by altagir** [comment]
yes thanks! it did fix it... fast response.
could you update pod version so fix is available?

**Comment by altagir** [comment]
could you push the fix? thanks

**Comment by daltoniam** [comment]
Certainly. Sorry about that delay, forgot to do this 😄. 3.0.1 is out and push to CocoaPods.
