### ISSUE TITLE
add name of property in the exception wrongType

### ISSUE THREAD

**Issue by altagir** [daltoniam/JSONJoy-Swift#52]
It would be very nice to have name of property when exception wrongType is fired
else debugging of model would be a pain

also ideally would say something like (exception wrongType for field 'address', 'string' expected', 'int' provided

**Comment by daltoniam** [comment]
Agreed. That will take a bit of effort, but certainly something to explore adding. PR welcomed if you have a solution.

**Comment by daltoniam** [comment]
I'm going to go ahead and close this out. The introduction of `Codable` in Swift 4 mostly deprecates JSONJoy. See the notice [here](https://github.com/daltoniam/JSONJoy-Swift#deprecation).
