### ISSUE TITLE
'JSONDecoder' has no member string

### ISSUE THREAD

**Issue by wscanf** [daltoniam/JSONJoy-Swift#53]
init(_ decoder: JSONDecoder) {
        display_name = decoder["display_name"].string

xcode 8 & swift 3

compiler says 'JSONDecoder' has no member string

how can I fix this?

**Comment by Ygilany** [comment]
any solution?

**Comment by daltoniam** [comment]
Version `3.0.0` simplified the get operation to `get` and the type is inferred. See the README for more info. You either need to update your code to the latest methods or use an older version of JSONJoy.
