### ISSUE TITLE
Parse String Array Issue

### ISSUE THREAD

**Issue by shalini90** [daltoniam/JSONJoy-Swift#55]
Please provide a sample snippet to parse a array of strings.

Eg.

{
"Places" : [
                 "Asia",
                 "Africa",
                 "America"
              ] 
}

I do not see a straight forward way to parse array of strings like this without a key.Please explain

**Comment by acmacalister** [comment]
```swift
struct Place : JSONJoy {
    let places: [String]

    init(_ decoder: JSONDecoder) throws {
        places = try decoder["Places"].get() //infers the type and returns a valid array
    }
}
```
