### ISSUE TITLE
Not working with Swift4

### ISSUE THREAD

**Issue by lennycampino** [daltoniam/JSONJoy-Swift#58]

**Comment by HqDGin** [comment]
It's because Swift4 has provided a type named 'JSONDecoder', as to my concern, that is much more easier to use, simply 'let p = try JSONDecoder.init().decode(Class.Type, from: data!)'.
Otherwise, you have to make a typealias of ModuleName.TypeName, in this case JSONJoy.JSONDecoder.

**Comment by jackcolley** [comment]
See my PR #59 - Until it is merged. Feel free to use my fork

**Comment by Alexsmile2010** [comment]
Please update your library for swift 4 support.

**Comment by jackcolley** [comment]
@Alexsmile2010 You can use my fork until my PR is merged. Just make sure you pull in the swift-4 branch

**Comment by Alexsmile2010** [comment]
How i can do that? Can you help me? I think I need set special link in cocoapods?

**Comment by jackcolley** [comment]
@Alexsmile2010 Sure - in your Podfile replace every reference to JSONJoy-Swift with this

`pod 'JSONJoy-Swift', :git => 'https://github.com/jackcolley/JSONJoy-Swift', :branch => 'swift-4'`

**Comment by daltoniam** [comment]
I just released version `3.0.2` with Swift 4 support. The JSONDecoder class has been renamed `JSONLoader` to fix the conflicts with Foundation. See the README for the updated examples and the deprecation [notice](https://github.com/daltoniam/JSONJoy-Swift#deprecation).
