### ISSUE TITLE
Update to xCode 9 and 'JSONDecoder' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by retuner87** [daltoniam/JSONJoy-Swift#60]
Hi, I've updated xCode to 9 and at the first build appear the error:

'JSONDecoder' is ambiguous for type lookup in this context

xCode find two JSONDecoder, one in Foundation and one in JSONJoy.
How can I solve it?

JSONJoy.JSONDecoder not works :(

Thanks in advance

**Comment by iMattDunbar** [comment]
You can fix this by just changing the name of the JSONDecoder in the class to something else.

I changed every reference to JSONDecoder in the folder to JSONDecoderX and all of my calls to it and it started working. Just FYI to the devs.

**Comment by daltoniam** [comment]
I just released version `3.0.2` with Swift 4 support. The JSONDecoder class has been renamed `JSONLoader` to fix the conflicts with Foundation. See the README for the updated examples and the deprecation [notice](https://github.com/daltoniam/JSONJoy-Swift#deprecation).
