### ISSUE TITLE
Swift 4 issue with 

### ISSUE THREAD

**Issue by LalitKY** [daltoniam/JSONJoy-Swift#61]
In below two functions

 /**
     get typed `Array` of `JSONJoy` and have it throw if it doesn't work
     */
    public func get<T: JSONJoy>() throws -> [T] {
        guard let a = getOptionalArray() else { throw JSONError.wrongType }
        return try a.reduce([T]()) { $0.0 + [try T($0.1)] }
    }
    
    /**
     get typed `Array` and have it throw if it doesn't work
     */
    open func get<T: JSONBasicType>() throws -> [T] {
        guard let a = getOptionalArray() else { throw JSONError.wrongType }
        return try a.reduce([T]()) { $0.0 + [try $0.1.get()] }
    }

In below two return values 

 return try a.reduce([T]()) { $0.0 + [try T($0.1)] }
 return try a.reduce([T]()) { $0.0 + [try $0.1.get()] }

Error = "Contextual type for closure argument list expects 1 argument, but 2 were specified". 

Update your code respectively.

**Comment by freddyKang** [comment]
i have same problem.......

**Comment by bohdanPaliychuk** [comment]
the same issue, do you how to fix it ?

**Comment by Asuard** [comment]
Hello, 

I have sent a PR ([#63](https://github.com/daltoniam/JSONJoy-Swift/pull/63) to fix this issue.

**Comment by daltoniam** [comment]
Thanks @Asuard. Version 3.0.3 has been released with the fix!
