### ISSUE TITLE
Swift4 compile error

### ISSUE THREAD

**Issue by freddyKang** [daltoniam/JSONJoy-Swift#62]
First of all, thank for your development.

My swift project made in swift 4 version, and JSONJoy 3.0.2 version.

I'm stuck in the error msg when complie. That msg was "Contextual closure type '(_, _) -> _' expects 2 arguments, but 1 was used in closure body"..

so i can't modify ..

the code is 

public func getOptional<T: JSONJoy>() -> [T]? {
        guard let a = getOptionalArray() else { return nil }
        do { return try a.reduce([T]()) { $0.0 + [try T($0.1)] } }
        catch { return nil }
}

**Comment by BhaveshKumbhani** [comment]
Same issue for me.

**Comment by bohdanPaliychuk** [comment]
the same issue, do you how to fix it ?

**Comment by daltoniam** [comment]
Version 3.0.3 has been released with the #63 fix!
